Favorite cities
tanaprog/Weather-List pull request #1
Opened 2024-02-24 12:39 UTC by tanaprog

Изменила функцию renderCityWeather - добавила в нее атрибут arrayList чтобы можно было отрисовывать 2 массива.

Добавила функции changeActiveBtnAllCities и changeActiveBtnFavorite (чтобы при добавлении карточки в Избранное или в Все Города менялась активная кнопка) в функцию  addCityWeatherInFavorite.

2024-02-25 18:57 UTC, tanaprog commented
Я подумав удалила 2 функции из функции addCityWeatherInFavorite строка 42. И сделала изменения в action = delete, так как увидела там ошибку при удалении карточки.

2024-02-28 16:30 UTC, ibulygin requested changes
И поправь баги

2024-02-28 16:30 UTC, ibulygin commented on src/index.js
> +function pushIconChangeClass(id) {
Мне не нравится название, тут же ты делаешь переключатель состояния isFavorite
А название про иконку, тут ты работаешь с данными они об иконках ничего не знают

тут придумай что-то типо toggleFavoriteCity

2024-02-28 16:30 UTC, ibulygin commented on src/index.js
> +function changeActiveBtnAllCities() {
Эту функцию лучше сделать универсальной
Что она делает? Добавляет класс к компоненту, название класса передаешь в аргументе функции, потому что потом если хахочешь еще что-то из классов доьавить

2024-02-28 16:30 UTC, ibulygin commented on src/index.js
> +function changeActiveBtnFavorite() {
Тоже самое

2024-02-28 16:30 UTC, ibulygin commented on src/index.js
>      console.log(CITY_WEATHER)
Убрать вывод в консоль, он тут не нужен, лишний код не влияет на логику

2024-02-28 16:30 UTC, ibulygin commented on src/index.js
> +function getCityFavoriteId(event) {
Кажется что getCityFavoriteId тоже не подходит, она же просто находит id ноды родителя
Тогла причем тут Favorite???

2024-03-01 14:29 UTC, tanaprog commented on src/index.js
> +function pushIconChangeClass(id) {
done

2024-03-01 14:30 UTC, tanaprog commented on src/index.js
> +function changeActiveBtnAllCities() {
done

2024-03-01 14:30 UTC, tanaprog commented on src/index.js
> +function changeActiveBtnFavorite() {
done

2024-03-01 14:30 UTC, tanaprog commented on src/index.js
>      console.log(CITY_WEATHER)
done

2024-03-01 14:30 UTC, tanaprog commented on src/index.js
> +function getCityFavoriteId(event) {
done

2024-03-01 14:42 UTC, tanaprog commented
Игорь, про баги... Я добавила обработку ошибки при некорректно введённом названии.
Изменила поведение карточки при добавлении в Избранное.

2024-03-23 09:41 UTC, ibulygin commented
комментарий

2024-03-23 09:47 UTC, ibulygin requested changes

2024-03-23 09:47 UTC, ibulygin commented on src/index.html
> +                <div class="favorit">
Давай почистим код, закоментированных и неиспользуемых строк не должно быть

2024-03-23 09:47 UTC, ibulygin commented on src/index.js
> +        if (CITY_WEATHER_FAVORITE) {
А вот эти условия зачем?

2024-03-23 09:47 UTC, ibulygin commented on src/index.js
> +        if (CITY_WEATHER) {
А вот эти условия зачем?

2024-03-23 09:47 UTC, ibulygin commented on src/index.js
>  function emptyText() {
название функции должно иметь нлагол то есть какое-то действие emptyText не подходит

Когда описываешь название, тебе нужно в имени сказать что делает твоя функция

2024-03-23 09:47 UTC, ibulygin commented on src/index.js
> +    const id = getElementId(e);
переменную ты нигде не используешь таки что она тут делает?   ю

2024-03-23 09:47 UTC, ibulygin commented on src/index.js
>  function emptyText() {
11111

2024-03-23 09:47 UTC, ibulygin commented on src/index.js
>  function emptyText() {
ф

2024-04-23 16:43 UTC, tanaprog commented
Переделала renderPopup функцию. Удалила все не нужное. Удалила функцию load() из функции getCityWeather().

2024-05-22 09:04 UTC, merged